theme: jekyll-theme-hacker
layout: agents
show_downloads: false
title: kaggle-agents-2025
description: "StockChat: Agents Edition"
kaggle_link: "https://www.kaggle.com/code/oswind/stockchat-agents-edition"
